### PR TITLE
Upgrade to Symfony 7

### PR DESCRIPTION
**Pull request by paullallier**
Hopefully this is useful - please just close if not wanted.

### CODE REVIEW

**Comment by paullallier** [comment]
Sorry - I should have checked #17. I think I have the released version of the packages now.

**Comment by paullallier** [comment]
No - I've lost proxy manager bridge.  I'm going to convert it back to draft so it's not accidentally merged.

**Comment by paullallier** [comment]
Ah.  It's deprecated in favour of VarExporter, which we have, but I'm not sure if that's sufficient:
Screenshot 2023-12-30 at 18 16 55

**Review by dunglas — APPROVED** [review]
LGTM

**Comment by dunglas** [comment]
Thank you!

**Pull request merged**
